Minor refactoring

diff --git a/pistar-update b/pistar-update
--- a/pistar-update
+++ b/pistar-update
@@ -34,11 +34,13 @@ hwDeetz="${hardwareField} - ${modelName}"
 uaStr="WPSD-ConnectivityCheck (Manual-Update) Ver.# ${psVer} ${versionCmd} (${W0CHP_DASH_BRANCH}) UUID:${uuidStr} [${hwDeetz}]"
 
 # connectivity check
-status_code=$(curl -m 3 -A "${uaStr}" --write-out %{http_code} --silent --output /dev/null "https://repo.w0chp.net/Chipster/W0CHP-PiStar-Dash.git/info/refs?service=git-upload-pack")
-if [[ "$status_code" -ne 200 ]] ; then
-    echo -e "Cannot reach git repository. Try again later. Exiting...\n"
-    exit 1
-fi
+conn_check() {
+    status_code=$(curl -m 3 -A "${uaStr}" --write-out %{http_code} --silent --output /dev/null "https://repo.w0chp.net/Chipster/W0CHP-PiStar-Dash.git/info/refs?service=git-upload-pack")
+    if [[ "$status_code" -ne 200 ]] ; then
+	echo -e "Cannot reach git repository. Try again later. Exiting...\n"
+	exit 1
+    fi
+}
 
 # maint. tasks
 /usr/local/sbin/wpsd-backend-maint > /dev/null 2>&1
@@ -191,6 +193,7 @@ git_update() {
 }
 
 main_function() {
+	conn_check
 	# Make the disk writable and stop cron to prevent it from making it R/O
     	systemctl stop cron.service > /dev/null 2<&1
     	pkill pistar-hourly.cron > /dev/null 2>&1
