* Minor: Improve and tweak modem detection routine and display

diff --git a/pistar-update b/pistar-update
--- a/pistar-update
+++ b/pistar-update
@@ -495,12 +495,17 @@ main_function() {
 		sed -i "/^date_default_timezone_set.*/i define('TIME_FORMAT', '24');" /var/www/dashboard/config/config.php
 	fi
 
-	# add modem cache to rc.local
-	if ! grep -q 'modemcache' /etc/rc.local ; then
-	    sed -i '/^\/usr\/local\/sbin\/pistar-motdgen/a \\n\n# cache modem info\n\/usr\/local\/sbin\/pistar-modemcache' /etc/rc.local 
-	    /usr/local/sbin/pistar-modemcache
+        # cleanup legacy naming convention
+        if grep -q 'modemcache' /etc/rc.local ; then
+            sed -i 's/modemcache/hwcache/g' /etc/rc.local
+	    sed -i 's/# cache modem info/# cache hw info/g' /etc/rc.local 
+        fi
+	# add hw cache to rc.local
+	if ! grep -q 'hwcache' /etc/rc.local ; then
+    	    sed -i '/^\/usr\/local\/sbin\/pistar-motdgen/a \\n\n# cache hw info\n\/usr\/local\/sbin\/pistar-hwcache' /etc/rc.local 
+	    /usr/local/sbin/pistar-hwcache
 	else
-	    /usr/local/sbin/pistar-modemcache
+	    /usr/local/sbin/pistar-hwcache
 	fi
 
 	# Add pistar-service bash completion
