* Intermediate: add git repo connectivity checks to maint. scripts.

diff --git a/pistar-update b/pistar-update
--- a/pistar-update
+++ b/pistar-update
@@ -4,7 +4,7 @@
 #                                                                             #
 #                        Pi-Star Auto Update Tool                             #
 #                                                                             #
-#    Version 3.10.8, Code, Design and Development by Andy Taylor (MW0MWZ)     #
+#    Version 3.10.9, Code, Design and Development by Andy Taylor (MW0MWZ)     #
 #                            Enhanced by W0CHP                                #
 #                                                                             #
 #                     Make it simple to update the OS.                        #
@@ -34,6 +34,14 @@ uuidStr=$( cat /etc/WPSD-release )
 modelName=$(grep -m 1 'model name' /proc/cpuinfo | sed 's/.*: //')
 hardwareField=$(grep 'Model' /proc/cpuinfo | sed 's/.*: //')
 hwDeetz="${hardwareField} - ${modelName}"
+uaStr="WPSD-ConnectivityCheck (Manual-Update) Ver.#${versionCmd} (${W0CHP_DASH_BRANCH}) UUID:${uuidStr} [${hwDeetz}]"
+
+# connectivity check
+status_code=$(curl -A "${uaStr}" --write-out %{http_code} --silent --output /dev/null https://repo.w0chp.net/Chipster/W0CHP-PiStar-Dash.git)
+if [[ "$status_code" -ne 200 ]] ; then
+    echo "Cannot reach git repository. Try again later. Exiting..."
+    exit 1
+fi
 
 function GetBinStatus() {
     dir="/usr/local/bin"
