* Minor: consolidate spec/version grabbing/caching funcs. Add logic to bootup to wait until all modem info is avaiable to populate

diff --git a/pistar-modemcache b/pistar-modemcache
--- a/pistar-modemcache
+++ b/pistar-modemcache
@@ -1,21 +1,33 @@
 #!/bin/bash
 
 mmdvmHostLog="/var/log/pi-star/MMDVM-*.log"
-_FWver=`grep 'MMDVM protocol version' ${mmdvmHostLog} | awk '{print $9}' | tail -1`
-_TCXO=`grep 'MMDVM protocol version' ${mmdvmHostLog} | awk '{print $11}' | tail -1`
-if ! grep -q 'MMDVM protocol version' ${mmdvmHostLog} ; then
-    exit 1
-else 
-    if ! grep -q 'Firmware' /etc/pistar-release > /dev/null; then
-        sed -i "/Hardware = /a Firmware = \nTCXO = " /etc/pistar-release
-        sed -i "/Firmware/c Firmware = $_FWver" /etc/pistar-release
-        sed -i "/TCXO/c TCXO = $_TCXO" /etc/pistar-release
-    else
-        sed -i "/Firmware/c Firmware = $_FWver" /etc/pistar-release
-        sed -i "/TCXO/c TCXO = $_TCXO" /etc/pistar-release
-    fi
-    sed -i '${/^$/d}' /etc/pistar-release
+
+# give a bit of time for MMDVMHost to generate the info in the logs before caching...
+while [ ! -f ${mmdvmHostLog} ]
+do
+    sleep 1
+done
+while [[ $( grep -c 'MMDVM protocol version' ${mmdvmHostLog} ) -eq 0 ]]
+do
+    mount -o remount,rw /
+    sleep 1
+done
+mount -o remount,rw /
+
+_FWver=$( grep 'MMDVM protocol version' ${mmdvmHostLog} | awk '{print $9}' | tail -1 )
+_TCXO=$( grep 'MMDVM protocol version' ${mmdvmHostLog} | awk '{print $11}' | tail -1 )
+
+if ! grep -q 'Firmware' /etc/pistar-release > /dev/null; then
+    sed -i "/Hardware = /a Firmware = \nTCXO = " /etc/pistar-release
+    sed -i "/Firmware/c Firmware = $_FWver" /etc/pistar-release
+    sed -i "/TCXO/c TCXO = $_TCXO" /etc/pistar-release
+else
+    sed -i "/Firmware/c Firmware = $_FWver" /etc/pistar-release
+    sed -i "/TCXO/c TCXO = $_TCXO" /etc/pistar-release
 fi
+
+# cleanup last line..
+sed -i '${/^$/d}' /etc/pistar-release
 
 countProcs=$(grep -c ^processor /proc/cpuinfo)
 if ! grep -w 'ProcNum' /etc/pistar-release > /dev/null; then
@@ -23,3 +35,12 @@ if ! grep -w 'ProcNum' /etc/pistar-release > /dev/null; then
 else
     sed -i "/ProcNum/c ProcNum = ${countProcs}" /etc/pistar-release
 fi
+
+_MMDVMHostVer=`MMDVMHost -v | awk '{ print $3 }'`
+sed -i "/MMDVMHost/c MMDVMHost = $_MMDVMHostVer" /etc/pistar-release
+
+sed -i "/ircddbgateway/c ircddbgateway = 20190621_W0CHP" /etc/pistar-release
+sed -i "/dstarrepeater/c dstarrepeater = 20180911_W0CHP" /etc/pistar-release
+
+_KernelVer=`uname -r`
+sed -i "/kernel/c kernel = $_KernelVer" /etc/pistar-release
