* Minor: if running update from terminal, ensure php74-zip is installed with Bullseye (daily-cron already does this, but still...)

diff --git a/pistar-update b/pistar-update
--- a/pistar-update
+++ b/pistar-update
@@ -226,6 +226,17 @@ main_function() {
 		apt-get update
 		apt-get upgrade --fix-missing --fix-broken -y
 		apt-get clean
+		# ensure bullseye has proper php extensions
+		dpkg --configure -a > /dev/null 2>&1
+		lsb_release -cs | grep 'bullseye' &> /dev/null
+		if [ $? == 0 ]; then
+		    if [ ! -f "/usr/share/php7.4-zip/zip/zip.ini" ] ; then
+			echo -e "Installing missing php-zip package..."
+		        apt-get install -y php-zip > /dev/null 2>&1
+		        apt-get clean > /dev/null 2<&1
+		        apt-get autoclean > /dev/null 2<&1
+		    fi
+		fi
 		echo -e "${TICK} Done!\n"
 
 		echo "Checking nginx web server config"
